import { StyleSheet } from "react-native";

export const colors = {
  slate900: "#0f172a",
  slate800: "#1e293b",
  slate700: "#334155",
  slate300: "#cbd5e1",
  slate100: "#f1f5f9",
  cyan: "#22d3ee",
  amber: "#f59e0b",
  emerald: "#22c55e",
  rose: "#f87171",
  matteBlack: "#0b0b0b",
  bountyGold: "#FFD760",
};

export const styles = StyleSheet.create({
  gradientBackground: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  body: {
    flex: 1,
  },
  scrollArea: {
    flex: 1,
  },
  footer: {
    backgroundColor: "transparent",
    paddingHorizontal: 10,
    paddingTop: 0,
    paddingBottom: 0,
    borderTopWidth: 0,
    elevation: 0,
    shadowOpacity: 0,
    overflow: "visible",
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
  },
  title: {
    color: colors.slate100,
    fontSize: 60,
    fontWeight: "800",
    fontFamily: "Poppins-Bold",
    textAlign: "center",
  },
  headerTitle: {
    flex: 1,
    textShadowColor: "#000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
  },
  tabRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    width: "100%",
    paddingTop: 0,
    paddingBottom: 0,
    height: 44,
    zIndex: 1,
  },
  tabButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  tabButtonActive: {
  },
  tabLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  tabLabelText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 12,
    textTransform: "lowercase",
    letterSpacing: 0.3,
  },
  tabLabelTextActive: {
    color: "#39ff14",
  },
  iconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  homeImage: {
    width: 40,
    height: 40,
    backgroundColor: "transparent",
  },
  ticketImage: {
    width: 40,
    height: 40,
    backgroundColor: "transparent",
  },
  profileImage: {
    width: 40,
    height: 40,
  },
  scrollContent: {
    padding: 16,
    gap: 12,
  },
  card: {
    backgroundColor: colors.slate800,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.slate700,
    gap: 10,
  },
  label: {
    color: colors.slate100,
    fontWeight: "700",
    fontSize: 16,
    letterSpacing: 0.3,
  },
  helper: {
    color: colors.slate300,
    fontSize: 14,
    lineHeight: 20,
  },
  ticketAllocated: {
    color: colors.emerald,
    fontSize: 13,
    fontWeight: "700",
    marginTop: 4,
  },
  fullMapContainer: {
    flex: 1,
    backgroundColor: colors.slate900,
    position: "relative",
  },
  headerOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
    zIndex: 2,
  },
  viewModeToggleRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 10,
    backgroundColor: "rgba(15,23,42,0.85)",
    padding: 6,
    borderRadius: 999,
    alignSelf: "center",
    borderWidth: 1,
    borderColor: colors.slate700,
  },
  viewModeButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "transparent",
  },
  viewModeButtonActive: {
    backgroundColor: colors.cyan,
  },
  viewModeButtonText: {
    color: colors.slate100,
    fontWeight: "700",
  },
  viewModeButtonTextActive: {
    color: colors.slate900,
  },
  fullMap: {
    ...StyleSheet.absoluteFillObject,
  },
  impactToast: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(34,211,238,0.12)",
    borderColor: "rgba(34,211,238,0.4)",
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  impactToastText: {
    color: colors.cyan,
    fontWeight: "800",
    fontSize: 12,
    letterSpacing: 0.3,
  },
  potholeMarkerDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "rgba(248,113,113,0.8)",
    borderWidth: 2,
    borderColor: "rgba(248,113,113,0.95)",
  },
  potholeCallout: {
    backgroundColor: "rgba(15,23,42,0.22)",
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: "rgba(248,113,113,0.45)",
    maxWidth: 220,
  },
  potholeCalloutTitle: {
    color: colors.slate100,
    fontWeight: "800",
    marginBottom: 2,
  },
  tripsDividerWrap: {
    width: "100%",
    alignSelf: "stretch",
    height: 10,
    justifyContent: "center",
    marginTop: 12,
    marginBottom: 16,
  },
  tripsDividerLine: {
    width: "100%",
    height: StyleSheet.hairlineWidth,
    opacity: 0.95,
  },
  tripsDividerGlow: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 6,
    opacity: 0.5,
  },
  potholeCalloutSeverity: {
    color: "#f87171",
    fontWeight: "700",
    marginTop: 4,
  },
  mapPlaceholder: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  viewModeMessage: {
    marginTop: 8,
    backgroundColor: "rgba(15,23,42,0.22)",
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    alignSelf: "center",
  },
  viewModeMessageText: {
    color: colors.slate100,
    fontWeight: "700",
    textAlign: "center",
  },
  legendPill: {
    marginTop: 8,
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.2)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,215,96,0.45)",
  },
  legendText: {
    color: colors.bountyGold,
    fontWeight: "700",
  },
  warnText: {
    color: colors.amber,
  },
  ghostBadge: {
    backgroundColor: "rgba(245,158,11,0.12)",
    borderColor: "rgba(245,158,11,0.28)",
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    alignSelf: "flex-start",
    marginTop: 8,
  },
  ghostBadgeText: {
    color: colors.amber,
    fontWeight: "700",
    fontSize: 12,
  },
  privacyNote: {
    color: colors.slate300,
    fontSize: 12,
    marginTop: 2,
  },
  valueNumberSmall: {
    color: colors.cyan,
    fontSize: 20,
    fontWeight: "700",
  },
  currentMultiplierValue: {
    color: colors.cyan,
    fontSize: 42,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  valueLabel: {
    color: colors.slate100,
    fontWeight: "600",
  },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  button: {
    paddingVertical: 12,
    alignItems: "center",
    borderRadius: 12,
    marginTop: 4,
  },
  secondary: {
    backgroundColor: colors.cyan,
  },
  muted: {
    backgroundColor: colors.slate700,
  },
  buttonText: {
    color: colors.slate900,
    fontWeight: "800",
    fontSize: 16,
  },
  buttonTextLight: {
    color: colors.slate100,
    fontWeight: "800",
    fontSize: 15,
  },
  smallButton: {
    paddingHorizontal: 12,
    flex: 1,
  },
  pill: {
    backgroundColor: colors.slate700,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  pillPositive: {
    backgroundColor: colors.emerald,
  },
  pillWarn: {
    backgroundColor: colors.amber,
  },
  pillText: {
    color: colors.slate100,
    fontWeight: "700",
  },
  pillTextDark: {
    color: colors.slate900,
  },
  merchantCard: {
    borderWidth: 1,
    borderColor: colors.slate700,
    borderRadius: 12,
    padding: 12,
    marginTop: 10,
    backgroundColor: "rgba(15,23,42,0.55)",
    gap: 10,
  },
  offerStack: {
    gap: 10,
  },
  offerItem: {
    borderBottomWidth: 1,
    borderBottomColor: colors.slate700,
    paddingVertical: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  offerMerchant: {
    color: colors.slate100,
    fontWeight: "700",
    fontSize: 15,
  },
  offerLabel: {
    color: colors.slate100,
    fontWeight: "600",
    flex: 1,
  },
  offerTierRow: {
    gap: 6,
    borderTopWidth: 1,
    borderTopColor: colors.slate700,
    paddingTop: 10,
  },
  offerTierRowFirst: {
    borderTopWidth: 0,
    paddingTop: 0,
  },
  offerTierPressable: {
    padding: 10,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  offerTierUsed: {
    opacity: 0.55,
  },
  offerTierHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  offerUsedLabel: {
    marginLeft: "auto",
    color: colors.slate300,
    fontWeight: "800",
    fontSize: 12,
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  tierBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: colors.emerald,
  },
  tierBadgeMuted: {
    backgroundColor: colors.slate700,
  },
  tierBadgeText: {
    color: colors.slate900,
    fontWeight: "800",
  },
  tierBadgeTextMuted: {
    color: colors.slate100,
  },
  unlockRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  usedOffersSection: {
    marginTop: 10,
    paddingTop: 10,
    gap: 6,
    borderTopWidth: 1,
    borderTopColor: colors.slate700,
  },
  usedOfferItem: {
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.slate700,
  },
  ruleDivider: {
    borderBottomWidth: 1,
    borderBottomColor: colors.slate700,
    marginVertical: 8,
  },
  streakBar: {
    backgroundColor: colors.slate700,
    height: 10,
    borderRadius: 999,
    overflow: "hidden",
  },
  streakFill: {
    backgroundColor: colors.emerald,
    width: "60%",
    height: "100%",
  },
  milestoneRow: {
    flexDirection: "row",
    gap: 12,
  },
  milestoneItem: {
    alignItems: "center",
    gap: 4,
  },
  missionsList: {
    gap: 10,
  },
  missionItem: {
    borderWidth: 1,
    borderColor: colors.slate700,
    borderRadius: 12,
    padding: 12,
    gap: 6,
    backgroundColor: "rgba(255,255,255,0.02)",
  },
  missionItemCompleted: {
    borderColor: colors.emerald,
    backgroundColor: "rgba(34,197,94,0.08)",
  },
  missionTitle: {
    color: colors.slate100,
    fontWeight: "700",
    fontSize: 15,
  },
  missionProgress: {
    color: colors.cyan,
    fontWeight: "800",
  },
  missionCompletedText: {
    color: colors.emerald,
    fontWeight: "700",
  },
  stepItem: {
    borderWidth: 1,
    borderColor: colors.slate700,
    borderRadius: 12,
    padding: 12,
    gap: 6,
  },
  stepHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  stepTitle: {
    color: colors.slate100,
    fontWeight: "700",
    fontSize: 15,
  },
  tightTop: {
    marginTop: 8,
  },
  ticketInfo: {
    flex: 1,
    paddingRight: 12,
    gap: 2,
  },
  ticketButton: {
    paddingHorizontal: 12,
    minWidth: 110,
  },
  ticketButtonDisabled: {
    opacity: 0.5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.55)",
    justifyContent: "flex-end",
  },
  modalBackdrop: {
    flex: 1,
  },
  modalCard: {
    backgroundColor: colors.slate800,
    padding: 16,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderWidth: 1,
    borderColor: colors.slate700,
    gap: 12,
  },
  allocationRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  counterButton: {
    backgroundColor: colors.slate700,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
    minWidth: 52,
    alignItems: "center",
  },
  counterButtonDisabled: {
    opacity: 0.5,
  },
  counterButtonText: {
    color: colors.slate100,
    fontWeight: "800",
    fontSize: 18,
  },
  allocationValue: {
    color: colors.cyan,
    fontSize: 26,
    fontWeight: "800",
    minWidth: 80,
    textAlign: "center",
  },
  modalActions: {
    flexDirection: "row",
    gap: 10,
  },
  redeemMessage: {
    color: colors.emerald,
    fontWeight: "700",
  },
  badgeGrid: {
    gap: 10,
  },
  badgeItem: {
    borderWidth: 1,
    borderColor: colors.slate700,
    borderRadius: 12,
    padding: 12,
    gap: 6,
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  badgeItemLocked: {
    opacity: 0.55,
  },
  badgeTitle: {
    color: colors.slate100,
    fontWeight: "700",
    fontSize: 15,
    flex: 1,
  },
  badgeDescription: {
    color: colors.slate300,
    fontSize: 13,
    lineHeight: 18,
  },
  badgeMeta: {
    color: colors.cyan,
    fontWeight: "700",
    fontSize: 12,
  },
  historyHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  historyItem: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.slate700,
  },
  historyTextGroup: {
    flex: 1,
    gap: 6,
  },
  historyDescription: {
    color: colors.slate100,
    fontWeight: "700",
    fontSize: 15,
  },
  historyMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  historySource: {
    color: colors.slate300,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  historyTime: {
    color: colors.slate300,
    fontSize: 12,
  },
  historyAmount: {
    fontWeight: "800",
    marginLeft: 12,
  },
  historyAmountEarn: {
    color: colors.emerald,
  },
  historyAmountSpend: {
    color: colors.rose,
  },
  historyEmpty: {
    alignItems: "flex-start",
    gap: 6,
  },
  historyBackButton: {
    flex: 0,
    paddingHorizontal: 14,
  },
  leaderboardToggleRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
    backgroundColor: "rgba(15,23,42,0.88)",
    padding: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.slate700,
  },
  leaderboardToggle: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  leaderboardToggleActive: {
    backgroundColor: colors.cyan,
  },
  leaderboardToggleText: {
    color: colors.slate100,
    fontWeight: "700",
  },
  leaderboardToggleTextActive: {
    color: colors.slate900,
  },
  leaderboardRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.slate700,
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  leaderboardUserRow: {
    borderColor: colors.cyan,
    backgroundColor: "rgba(34,211,238,0.1)",
  },
  leaderboardIdentity: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    gap: 10,
  },
  leaderboardRank: {
    color: colors.slate300,
    fontWeight: "800",
    width: 50,
  },
  leaderboardName: {
    color: colors.slate100,
    fontWeight: "700",
    flexShrink: 1,
  },
  leaderboardScore: {
    color: colors.cyan,
    fontWeight: "800",
  },
  leaderboardAvatarWrapper: {
    width: 42,
    height: 42,
    borderRadius: 21,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    overflow: "hidden",
  },
  leaderboardAvatarGlow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 21,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
  },
  leaderboardAvatarGlowUser: {
    backgroundColor: "rgba(34,211,238,0.16)",
    borderColor: colors.cyan,
  },
  leaderboardAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.2)",
  },
  profileTabAvatarWrapper: {
    overflow: "hidden",
  },
  profileTabAvatarWrapperActive: {
    shadowColor: colors.cyan,
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
  },
  profileTabAvatarGlow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 22,
    opacity: 0.9,
  },
  profileTabAvatarImage: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 2,
    borderColor: "rgba(57,255,20,0.6)",
  },
});
